In [2]:
import pandas as pd
import numpy as np

Forecast JB analysis

In [39]:
jb18 = pd.read_csv('csv_raw_data/Jabil_2018.csv')

In [40]:
cols_name = list(jb18.columns.values)
print(cols_name)

['COMPANY', 'BILLTO', 'MRPVSCONT', 'NUM_FPN', 'NUM_CPN', 'CPN', 'MFR', 'MFR_PART', 'FPN', 'PRIORITY', 'CLASS', 'EAU', 'BOND_QTY', 'BOND_DELTA', 'BOND_ALLOC', 'ATS_BOL', 'ATS_MTL', 'ATS_ASIA', 'ATS_EUR', 'DELTA', 'WKS_SUPPLY', 'CUTOFFDATE', 'TREND', 'VOLAT_PERC', 'ACCUR_PERC', 'TOTAL_CBO', 'TOT_ALLOC', 'PROV_ALLOC', 'NA_PBO', 'EUR_PBO', 'ASIA_PBO', 'USE_1_12', 'USE_13_24', 'USE_13_16', 'USE_9_12', 'USE_5_8', 'USE_1_4', 'PASTDUE', 'WEEK1', 'WEEK2', 'WEEK3', 'WEEK4', 'WEEK5', 'WEEK6', 'MRP_1_4', 'MRP_5_8', 'MRP_9_12', 'MRP_13_16', 'MRP_17_20', 'MRP_21_24', 'MRP_25_28', 'MRP_OVER28', 'MRP_1_12', 'GROSS_NET', 'QOH', 'FCQOH', 'INTRANSIT', 'FRESALE', 'UOM', 'CRESALE', 'RESCHK', 'PRODUCTYPE', 'FMPQ', 'CMPQ', 'MPQCHK', 'CPNDESC', 'BIN_LOC', 'CONTR_NUM', 'CONTR_LINE', 'CONTR_STRT', 'CONTR_END', 'EXTRA1', 'EXTRA2', 'EXTRA3', 'LOI_NUM', 'CUST_PO', 'CUSTPOLINE', 'IS_LF', 'IS_ROHS', 'A_LF_PB', 'A_ROHS', 'END_CUST', 'PROG_PART', 'WEEK13', 'MRPPD_13', 'NET_90DAY', 'RUN_DATE', 'PAPER_WORK', 'NETGRECEIV', 'QOHDEDUCT', 'CBODEDUCT', 'FCQOHDEDUC', 'CUST_NET90', 'ACTIONET90', 'CBOBONDALC', 'CODE', 'NOTES', 'USERNAME', 'MODDATE', 'MANUALOC', 'LEADTIME', 'CUSTMPN']

In [41]:
jb18 = jb18[['NUM_FPN', 'NUM_CPN', 'CPN', 'MFR', 'MFR_PART','MRP_1_4', 'MRP_5_8', 'MRP_9_12', 'MRP_13_16', 'MRP_17_20', 'MRP_21_24', 'MRP_25_28', 'MRP_OVER28','QOH']]
jb18.rename(columns={'MRP_1_4': 'Jan/2018','MRP_5_8': 'Feb/2018','MRP_9_12':'Mar/2018','MRP_13_16':'Apr/2018','MRP_17_20':'May/2018','MRP_21_24':'Jun/2018','MRP_25_28':'Jul/2018','MRP_OVER28':'Aug18onw'}, inplace=True)

In [42]:
jb18.head(2)

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2018,Feb/2018,Mar/2018,Apr/2018,May/2018,Jun/2018,Jul/2018,Aug18onw,QOH
0,1,1,12-1044,DIO,SMAZ20-13-F,130210,69920,138150,88960,78648,85432,88320,238720,91997
1,1,1,12-1070,DIO,B340A-13-F,130210,69920,138150,88960,78648,85432,88320,238720,92222

In [43]:
jb19 = pd.read_csv('csv_raw_data/Jabil_2019.csv')
jb20 = pd.read_csv('csv_raw_data/Jabil_2020.csv')
jb21 = pd.read_csv('csv_raw_data/Jabil_2021.csv')
jb22 = pd.read_csv('csv_raw_data/Jabil_2022.csv')

In [44]:
jb19 = jb19[['NUM_FPN', 'NUM_CPN', 'CPN', 'MFR', 'MFR_PART','MRP_1_4', 'MRP_5_8', 'MRP_9_12', 'MRP_13_16', 'MRP_17_20', 'MRP_21_24', 'MRP_25_28', 'MRP_OVER28','QOH']]
jb19.rename(columns={'MRP_1_4': 'Jan/2019','MRP_5_8': 'Feb/2019','MRP_9_12':'Mar/2019','MRP_13_16':'Apr/2019','MRP_17_20':'May/2019','MRP_21_24':'Jun/2019','MRP_25_28':'Jul/2019','MRP_OVER28':'Aug19onw'}, inplace=True)
jb20 = jb20[['NUM_FPN', 'NUM_CPN', 'CPN', 'MFR', 'MFR_PART','MRP_1_4', 'MRP_5_8', 'MRP_9_12', 'MRP_13_16', 'MRP_17_20', 'MRP_21_24', 'MRP_25_28', 'MRP_OVER28','QOH']]
jb20.rename(columns={'MRP_1_4': 'Jan/2020','MRP_5_8': 'Feb/2020','MRP_9_12':'Mar/2020','MRP_13_16':'Apr/2020','MRP_17_20':'May/2020','MRP_21_24':'Jun/2020','MRP_25_28':'Jul/2020','MRP_OVER28':'Aug20onw'}, inplace=True)

jb21 = jb21[['NUM_FPN', 'NUM_CPN', 'CPN', 'MFR', 'MFR_PART','MRP_1_4', 'MRP_5_8', 'MRP_9_12', 'MRP_13_16', 'MRP_17_20', 'MRP_21_24', 'MRP_25_28', 'MRP_OVER28','QOH']]
jb21.rename(columns={'MRP_1_4': 'Jan/2021','MRP_5_8': 'Feb/2021','MRP_9_12':'Mar/2021','MRP_13_16':'Apr/2021','MRP_17_20':'May/2021','MRP_21_24':'Jun/2021','MRP_25_28':'Jul/2021','MRP_OVER28':'Aug21onw'}, inplace=True)
jb22 = jb22[['NUM_FPN', 'NUM_CPN', 'CPN', 'MFR', 'MFR_PART','MRP_1_4', 'MRP_5_8', 'MRP_9_12', 'MRP_13_16', 'MRP_17_20', 'MRP_21_24', 'MRP_25_28', 'MRP_OVER28','QOH']]
jb22.rename(columns={'MRP_1_4': 'Jan/2022','MRP_5_8': 'Feb/2022','MRP_9_12':'Mar/2022','MRP_13_16':'Apr/2022','MRP_17_20':'May/2022','MRP_21_24':'Jun/2022','MRP_25_28':'Jul/2022','MRP_OVER28':'Aug22onw'}, inplace=True)

In [45]:
jb20.head(2)

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2020,Feb/2020,Mar/2020,Apr/2020,May/2020,Jun/2020,Jul/2020,Aug20onw,QOH
0,1,1,12-04134,DIO,RS1MSWF-7,20000,22000,0,53000,0,0,7000,40000,82628
1,1,1,12-04135,DIO,BAV116WS-7,40000,44000,0,106000,0,0,14000,80000,162544

In [46]:
jb22.head(2)

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2022,Feb/2022,Mar/2022,Apr/2022,May/2022,Jun/2022,Jul/2022,Aug22onw,QOH
0,1,1,12-04135,DIO,BAV116WS-7,179880,158400,205200,214200,55800,59400,63000,248400,263577
1,1,1,12-04150,DIO,D5V0L1B2T-7,274289,243900,307800,353700,89100,100800,112500,444600,409342

In [47]:
a = np.intersect1d(jb19.columns, jb21.columns)
print (a)

['CPN' 'MFR' 'MFR_PART' 'NUM_CPN' 'NUM_FPN' 'QOH']

In [48]:
merged_1 = pd.merge(jb18, jb19, on=['CPN','MFR','MFR_PART','NUM_CPN','NUM_FPN'], how='left')

In [49]:
merged_1

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2018,Feb/2018,Mar/2018,Apr/2018,May/2018,...,QOH_x,Jan/2019,Feb/2019,Mar/2019,Apr/2019,May/2019,Jun/2019,Jul/2019,Aug19onw,QOH_y
0,1,1,12-1044,DIO,SMAZ20-13-F,130210,69920,138150,88960,78648,...,91997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,12-1070,DIO,B340A-13-F,130210,69920,138150,88960,78648,...,92222,888.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6473.0
2,1,1,13-1042,DIO,BSS123-7-F,390630,209760,414450,266880,235944,...,275129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,1,15-1327,CIT,CMR200T32768DZFT,130210,69920,138150,88960,78648,...,92522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1,188735397,DIO,BAV99W-7-F,23687,10946,19016,18813,22697,...,33880,12148.0,10131.0,12016.0,8170.0,15131.0,19781.0,18016.0,93984.0,22173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,1,1,ECMP000025,LF,1.5KE250CA,0,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1,1,ECMP000200,ABR,ABS07-151-32.768KHZ-T,0,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1,1,ECMP000504,ABR,AB26TRQ-32.768KHZ-T,0,0,0,0,0,...,0,112976.0,65344.0,129600.0,144592.0,187200.0,231600.0,186000.0,468880.0,32719.0
101,1,1,GE9938048007,MCP,AT24C128C-SSHM-T,0,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2,1,GE9938052116,DIO,BAT54S-7-F,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
merged_2 = pd.merge(merged_1, jb20, on=['CPN','MFR','MFR_PART','NUM_CPN','NUM_FPN'], how='left')

In [51]:
merged_2

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2018,Feb/2018,Mar/2018,Apr/2018,May/2018,...,QOH_y,Jan/2020,Feb/2020,Mar/2020,Apr/2020,May/2020,Jun/2020,Jul/2020,Aug20onw,QOH
0,1,1,12-1044,DIO,SMAZ20-13-F,130210,69920,138150,88960,78648,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,12-1070,DIO,B340A-13-F,130210,69920,138150,88960,78648,...,6473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,13-1042,DIO,BSS123-7-F,390630,209760,414450,266880,235944,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,1,15-1327,CIT,CMR200T32768DZFT,130210,69920,138150,88960,78648,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,188735397,DIO,BAV99W-7-F,23687,10946,19016,18813,22697,...,22173.0,8998.0,7728.0,11228.0,7758.0,9299.0,4088.0,4414.0,15973.0,17264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,1,1,ECMP000025,LF,1.5KE250CA,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1,1,ECMP000200,ABR,ABS07-151-32.768KHZ-T,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1,1,ECMP000504,ABR,AB26TRQ-32.768KHZ-T,0,0,0,0,0,...,32719.0,70862.0,85664.0,86000.0,104000.0,60000.0,78000.0,114000.0,154160.0,61665.0
101,1,1,GE9938048007,MCP,AT24C128C-SSHM-T,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2,1,GE9938052116,DIO,BAT54S-7-F,0,0,0,0,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
merged_3 = pd.merge(merged_2, jb21, on=['CPN','MFR','MFR_PART','NUM_CPN','NUM_FPN'], how='left')

C:\Users\DELL\AppData\Local\Temp\ipykernel_15660\2006488798.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'QOH_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_3 = pd.merge(merged_2, jb21, on=['CPN','MFR','MFR_PART','NUM_CPN','NUM_FPN'], how='left')

In [53]:
merged_3

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2018,Feb/2018,Mar/2018,Apr/2018,May/2018,...,QOH_x,Jan/2021,Feb/2021,Mar/2021,Apr/2021,May/2021,Jun/2021,Jul/2021,Aug21onw,QOH_y
0,1,1,12-1044,DIO,SMAZ20-13-F,130210,69920,138150,88960,78648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,12-1070,DIO,B340A-13-F,130210,69920,138150,88960,78648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,13-1042,DIO,BSS123-7-F,390630,209760,414450,266880,235944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,1,15-1327,CIT,CMR200T32768DZFT,130210,69920,138150,88960,78648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,188735397,DIO,BAV99W-7-F,23687,10946,19016,18813,22697,...,17264.0,10306.0,5060.0,15774.0,11805.0,8894.0,14323.0,10298.0,38513.0,11666.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,1,1,ECMP000025,LF,1.5KE250CA,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1,1,ECMP000200,ABR,ABS07-151-32.768KHZ-T,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1,1,ECMP000504,ABR,AB26TRQ-32.768KHZ-T,0,0,0,0,0,...,61665.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101,1,1,GE9938048007,MCP,AT24C128C-SSHM-T,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2,1,GE9938052116,DIO,BAT54S-7-F,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
merged_4 = pd.merge(merged_3, jb22, on=['CPN','MFR','MFR_PART','NUM_CPN','NUM_FPN'], how='left')

In [55]:
merged_4

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2018,Feb/2018,Mar/2018,Apr/2018,May/2018,...,QOH_y,Jan/2022,Feb/2022,Mar/2022,Apr/2022,May/2022,Jun/2022,Jul/2022,Aug22onw,QOH
0,1,1,12-1044,DIO,SMAZ20-13-F,130210,69920,138150,88960,78648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,12-1070,DIO,B340A-13-F,130210,69920,138150,88960,78648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,13-1042,DIO,BSS123-7-F,390630,209760,414450,266880,235944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,1,15-1327,CIT,CMR200T32768DZFT,130210,69920,138150,88960,78648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,188735397,DIO,BAV99W-7-F,23687,10946,19016,18813,22697,...,11666.0,2420.0,29678.0,22276.0,14751.0,7773.0,9862.0,9355.0,62392.0,43752.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,1,1,ECMP000025,LF,1.5KE250CA,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1,1,ECMP000200,ABR,ABS07-151-32.768KHZ-T,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1,1,ECMP000504,ABR,AB26TRQ-32.768KHZ-T,0,0,0,0,0,...,0.0,79991.0,106400.0,84000.0,121564.0,143650.0,149280.0,70329.0,277022.0,421190.0
101,1,1,GE9938048007,MCP,AT24C128C-SSHM-T,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2,1,GE9938052116,DIO,BAT54S-7-F,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df_filled = merged_4.fillna(0)

In [57]:
df_filled.drop(['QOH_x', 'QOH_y', 'QOH'], axis=1, inplace=True)

In [58]:
df_filled.head(3)

,NUM_FPN,NUM_CPN,CPN,MFR,MFR_PART,Jan/2018,Feb/2018,Mar/2018,Apr/2018,May/2018,...,Jul/2021,Aug21onw,Jan/2022,Feb/2022,Mar/2022,Apr/2022,May/2022,Jun/2022,Jul/2022,Aug22onw
0,1,1,12-1044,DIO,SMAZ20-13-F,130210,69920,138150,88960,78648,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,12-1070,DIO,B340A-13-F,130210,69920,138150,88960,78648,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,1,13-1042,DIO,BSS123-7-F,390630,209760,414450,266880,235944,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
mean18 = df_filled['Aug18onw']/5
mean19 = df_filled['Aug19onw']/5
mean20 = df_filled['Aug20onw']/5
mean21 = df_filled['Aug21onw']/5
mean22 = df_filled['Aug21onw']/5

In [60]:
position = df_filled.columns.get_loc('Aug18onw')
print(position)

12

In [73]:
#merged_3.drop(['Aug20'], axis=1, inplace=True)

In [61]:
new_cols = {'Aug/2018': mean18,
            'Sep/2018': mean18,
            'Oct/2018': mean18,
            'Nov/2018': mean18,
            'Dec/2018': mean18}

insert_position = 13
for col_name, col_values in new_cols.items():
    df_filled.insert(insert_position, col_name, col_values)
    insert_position += 1

In [62]:
position = df_filled.columns.get_loc('Aug19onw')
print(position)

25

In [63]:
new_colss = {'Aug/2019': mean19,
            'Sep/2019': mean19,
            'Oct/2019': mean19,
            'Nov/2019': mean19,
            'Dec/2019': mean19}

insert_positions = 26
for col_name, col_values in new_colss.items():
    df_filled.insert(insert_positions, col_name, col_values)
    insert_positions += 1

In [64]:
position = df_filled.columns.get_loc('Aug20onw')
print(position)

38

In [65]:
new_colsss = {'Aug/2020': mean20,
            'Sep/2020': mean20,
            'Oct/2020': mean20,
            'Nov/2020': mean20,
            'Dec/2020': mean20}

insert_positionss = 39
for col_name, col_values in new_colsss.items():
    df_filled.insert(insert_positionss, col_name, col_values)
    insert_positionss += 1

In [66]:
position = df_filled.columns.get_loc('Aug21onw')
print(position)

51

In [67]:
new_colssss = {'Aug/2021': mean21,
            'Sep/2021': mean21,
            'Oct/2021': mean21,
            'Nov/2021': mean21,
            'Dec/2021': mean21}

insert_positionsss = 52
for col_name, col_values in new_colssss.items():
    df_filled.insert(insert_positionsss, col_name, col_values)
    insert_positionsss += 1

In [68]:
position = df_filled.columns.get_loc('Aug22onw')
print(position)

64

In [69]:
new_colsssss = {'Aug/2022': mean22,
            'Sep/2022': mean22,
            'Oct/2022': mean22,
            'Nov/2022': mean22,
            'Dec/2022': mean22}

insert_positionssss = 65
for col_name, col_values in new_colsssss.items():
    df_filled.insert(insert_positionssss, col_name, col_values)
    insert_positionssss += 1

In [70]:
df_filled.drop(['Aug18onw','Aug19onw','Aug20onw','Aug21onw','Aug22onw'], axis=1, inplace=True)

In [71]:
df_filled.to_csv('cleaned_forecast.csv', index = False)

PDA data analysis

In [78]:
try:
    pda = pd.read_csv('csv_raw_data/PDA_data.csv', encoding='latin-1')  
    print(pda.head())  
except UnicodeDecodeError as e:
    print(f"UnicodeDecodeError: {e}")
    # Handle the error appropriately
except FileNotFoundError as e:
    print(f"FileNotFoundError: {e}")
    # Handle the error appropriately

      Group TERRITORY PAST_DUE_DAYS_CRD PAST_DUE_DAYS_ORD_STATUS  \
0  Discrete     ASEAN         > 14 Days                > 14 Days
1  Discrete     ASEAN         > 14 Days                > 14 Days
2   Passive     ASEAN        <= 14 Days               <= 14 Days
3   Passive     ASEAN         > 14 Days               <= 14 Days
4  Discrete     ASEAN        <= 14 Days               <= 14 Days

   PAST_DUE_ORD_STATUS_DAYCOUNT ALGO  Comp  Br Region BRANCH NAME  ...  \
0                           108  DDB  FUTA  2R  ASEAN     VIETNAM  ...
1                           202  DDB  FUTA  2R  ASEAN     VIETNAM  ...
2                            13  BBA  FUTA  2R  ASEAN     VIETNAM  ...
3                            13  BBA  FUTA  01  ASEAN   SINGAPORE  ...
4                             3  DDA  FUTA  01  ASEAN   SINGAPORE  ...

  Follow_Up DIW BL Repl Day Count Change Queue  \
0       NaN      0            NaN
1       NaN      0            NaN
2       NaN   E  0            2.0
3       NaN      0            2.0
4       NaN      0            NaN

                                        CCA_Comments CCA_Follow_Up IMP Says  \
0  06/14 - 43 aging days;Overdue account (Shirlla...           NaN
1  06/14 - 43 aging days;Overdue account (Shirlla...           NaN
2                                                              NaN
3                                                              NaN
4                                                              NaN

  Agreed Last Comment Flag
0      0
1      0
2      0
3      0
4      0

[5 rows x 121 columns]

In [79]:
pda_cols_name = list(pda.columns.values)
print(pda_cols_name)

['Group', 'TERRITORY', 'PAST_DUE_DAYS_CRD', 'PAST_DUE_DAYS_ORD_STATUS', 'PAST_DUE_ORD_STATUS_DAYCOUNT', 'ALGO', 'Comp', 'Br', 'Region', 'BRANCH NAME', 'COUNTRY MANAGER', 'BRANCH MANAGER', 'IS MANAGER', 'FAI SENIOR MANAGER', 'BillTo', 'BILL_NAME', 'Shipto', 'Customer Name', 'Business Unit', 'Cl', 'GenericMFR', 'Mfr', 'Pt', 'Future Part #', 'Customer Part #', 'MFR Part #', 'Part Description', 'CAT', 'Order Number', 'Ln', 'Cust PO Line', ' Value ', ' Value-Alloc ', 'Ordered', 'Required', 'Commited', 'Orig Req Date', 'Sort Code', 'Stat', 'StatChecker', 'Status Description', 'Resale', 'U', 'Cur', 'Currency Rate', 'Qty', 'Alloc', 'Balance', 'Mtl Avl', 'Bos Avl', 'UK Avl', 'Asia Avl', 'Int Mtl', 'Int Bos', 'PBO', 'CBO', 'POQ', 'MPQ', 'SOQ', 'Mrp 30', 'Mrp 60', 'Mrp 90', 'Col', 'FAI', 'Mrp 120', 'Mrp Date', '# of Resched', 'PBO Order', 'PBO Line', 'PBO Qty', 'PBO Req Date', 'PBO Commit Date', 'PBO CheckDate', 'PBO Count', 'PBO VendorCode', 'Last Alloc Date', 'Rk', 'Nc', 'M', 'RedFlag', 'Bonds Exists', 'InvoiceNo', 'ViaCode', 'Waybill', 'Tariff Class', 'ECCN', 'HS Code', 'HS Description', 'Terms', 'LeadTime', 'Order Entry LT', 'IS Name', 'OS Name', 'Is', 'Os', 'CSA', 'Buyer Name', 'ShipComplete', 'Source', 'USTR Section 301', 'Exempt Reason', 'Future Surcharge', 'Importer of Record', 'Applies to Cust', 'Expedite Feedback', 'Exp Says Date', 'In House Comments', 'Comments', 'Notes', 'TSG Action', 'Branch Action', 'Follow_Up', 'DIW', 'BL', 'Repl Day Count', 'Change Queue', 'CCA_Comments', 'CCA_Follow_Up', 'IMP Says', 'Agreed', 'Last Comment Flag']

In [82]:
pda2 = pda[['Group','PAST_DUE_DAYS_ORD_STATUS','PAST_DUE_ORD_STATUS_DAYCOUNT','BRANCH NAME','BILL_NAME','Business Unit','Mfr','Customer Part #','MFR Part #','CAT','Order Number',' Value ', ' Value-Alloc ','Ordered','Required','Commited','Resale','Qty','Alloc','Balance', 'Mtl Avl', 'Bos Avl', 'UK Avl', 'Asia Avl','PBO', 'CBO', 'POQ', 'MPQ', 'SOQ','ViaCode','Tariff Class','OS Name']]
pda2.head(3)

,Group,PAST_DUE_DAYS_ORD_STATUS,PAST_DUE_ORD_STATUS_DAYCOUNT,BRANCH NAME,BILL_NAME,Business Unit,Mfr,Customer Part #,MFR Part #,CAT,...,UK Avl,Asia Avl,PBO,CBO,POQ,MPQ,SOQ,ViaCode,Tariff Class,OS Name
0,Discrete,> 14 Days,108,VIETNAM,BINH ANH ELECTRONIC TECH DEVT CO,Discrete,EVL,VT-00379,17-215SURC/S530-A3/TR8,1,...,0,102000,0,201000,21000,3000,3000,ASSAFCA,LL009,"NGUYEN, ALBERT (A-2R)"
1,Discrete,> 14 Days,202,VIETNAM,BINH ANH ELECTRONIC TECH DEVT CO,Discrete,EVL,17-215SURC/S530-A3/TR8,17-215SURC/S530-A3/TR8,1,...,0,102000,0,201000,21000,3000,3000,ASSAFCA,LL009,"NGUYEN, ALBERT (A-2R)"
2,Passive,<= 14 Days,13,VIETNAM,CICOR ASIA PTE LTD,Passive,SMP,4096842,CL05A106MQ5NUNC,1,...,810000,2050000,1410000,4360000,50000,10000,10000,ASSAFCA,KK123,"VO, DUCHIEU (A-2R)"

In [83]:
final_pda = pda2.fillna(0)

In [85]:
final_pda.to_csv('C:\\Users\\DELL\\Documents\\Dissert Project\\Visualize\\cleaned_pda.csv', index = False)

Backlog Delivery

In [12]:
bd = pd.read_csv('csv_raw_data/Backorder_Delivery.csv')

In [13]:
bd

,Company,Ship To,Customer Name,Customer Part.,Mfr,Mfr Part.,Future Part.,Item No,Order Number,Line Number,...,MSR Email,ProductSpecialist Email,Business Unit,Action group (short),Debit No,PBO OrderNo,PBO OrderLine,PBO OrderSubLine,PBO Qty,Manual Allocation
0,FUTA,JS005B00,JABIL VIETNAM CO. LTD.,189103664,DIO,BZT52C43-7-F,BZT52C43TR,7388556,BIM-JABIL VN-SMCI,9,...,Rini.Rashid@FutureElectronics.com,Wandy.Liean@FutureElectronics.com,Small Signal Discretes,Man Alloc,#INVALID,NaN,NaN,NaN,0,1
1,FUTA,JS004000,JABIL VIETNAM CO. LTD,SND1DDE002302-NR,DIO,BAV70DW-7-F,BAV70DWTR,4456992,4508650451,1,...,Rini.Rashid@FutureElectronics.com,Wandy.Liean@FutureElectronics.com,Small Signal Discretes,Man Alloc,D881472,NaN,NaN,NaN,0,1
2,FUTA,JS004000,JABIL VIETNAM CO. LTD,CA763-00012-LC,DIO,DSS8110Y-7,DSS8110Y-7,7091728,4508909383,1,...,Rini.Rashid@FutureElectronics.com,KiKi.Chen@FutureElectronics.com,Discretes,Man Alloc,NO SSD REQD,NaN,NaN,NaN,0,1
3,FUTA,JS004000,JABIL VIETNAM CO. LTD,SEECS-FT-20060-LF,DIO,ZVN3320FTA,ZVN3320FTA,7362841,4509263942,1,...,Rini.Rashid@FutureElectronics.com,Wandy.Liean@FutureElectronics.com,Small Signal Discretes,Man Alloc,D881472,NaN,NaN,NaN,0,1
4,FUTA,JS080200,JABIL VIETNAM CO. LTD.,SW5010155,DIO,DMN32D2LFB4-7,DMN32D2LFB4TR-JABIL,2132320,1852055747,1,...,Rini.Rashid@FutureElectronics.com,KiKi.Chen@FutureElectronics.com,Discretes,Man Alloc,D882505,NaN,NaN,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083,FUTA,JS004000,JABIL VIETNAM CO. LTD,ZB-CR000457A01,SEM,UCLAMP0571P.TNT,UCLAMP0571P.TNT/ZEBRA,8142023,4510992686,1,...,Adarsh.HP@FutureElectronics.com,JingHoe.Choo@FutureElectronics.com,Circuit Protection,Date <=7d,#NON SSD MFR,CCV8EH,1.0,1.0,30000,0
1084,FUTA,JS004000,JABIL VIETNAM CO. LTD,62711-45,DIO,LM2903S-13,LM2903MX,1058804,4510994395,1,...,Rini.Rashid@FutureElectronics.com,Sharon.Lai@FutureElectronics.com,ANALOG,Purch,NO SSD REQD,NaN,NaN,NaN,0,0
1085,FUTA,JS004000,JABIL VIETNAM CO. LTD,62711-45,DIO,LM2903S-13,LM2903MX,1058804,4510994396,1,...,Rini.Rashid@FutureElectronics.com,Sharon.Lai@FutureElectronics.com,ANALOG,Purch,NO SSD REQD,NaN,NaN,NaN,0,0
1086,FUTA,JS010600,JABIL VIETNAM CO. LTD.,192039313,NXP,NX5L2750CGUX,NX5L2750CGUX-JABIL,6095769,1852141077,1,...,YuLing.Lim@FutureElectronics.com,Jaslyn.Aw@FutureElectronics.com,ANALOG,Purch,#EXP_D1397500,NaN,NaN,NaN,0,0
1087,FUTA,JS004000,JABIL VIETNAM CO. LTD,SNDHUA39594-NR,DIO,BC857BLP4-7B,BC857BLP4-7B,3067082,4510995656,1,...,Rini.Rashid@FutureElectronics.com,Wandy.Liean@FutureElectronics.com,Small Signal Discretes,Purch,D882515,NaN,NaN,NaN,0,0

In [14]:
bd_cols_name = list(bd.columns.values)
print(bd_cols_name)

['Company', 'Ship To', 'Customer Name', 'Customer Part.', 'Mfr', 'Mfr Part.', 'Future Part.', 'Item No', 'Order Number', 'Line Number', 'Customer PO Line (numeric)', 'Date Ordered', 'Date Required', 'Qty Required', 'Qty Allocated', 'Current Customer Commit', 'Current Commit Date', 'Resale Price', 'Value USD', 'Value Alloc USD', 'Date Code', 'LeadTime', 'Product Type', 'MPQ', 'Class', 'Status Description', 'Ship (Transport) Date', 'Value Added', 'Invoice Number', 'Usage Last Month', 'Usage 2 Mths ago', 'Usage 3 Mths ago', 'Total PBO Qty', 'Country Of Origin', 'Weight(grams)', 'Via Code', 'HS Code', 'HS Description', 'Reject Reason', 'Stock Asia', 'Stock Asia Available', 'Stock Canada', 'Stock Canada Available', 'Stock Europe', 'Stock Europe Available', 'Stock US', 'Stock US Available', 'Buyer Name', 'OS Email', 'IS Email', 'CSA', 'AssetManager Email', 'MSR Email', 'ProductSpecialist Email', 'Business Unit', 'Action group (short)', 'Debit No', 'PBO OrderNo', 'PBO OrderLine', 'PBO OrderSubLine', 'PBO Qty', 'Manual Allocation']

In [15]:
bd1 = bd[['Ship To', 'Customer Name', 'Customer Part.', 'Mfr','Item No', 'Order Number','Date Ordered', 'Date Required', 'Qty Required', 'Qty Allocated', 'Current Customer Commit', 'Current Commit Date', 'Resale Price', 'Value USD', 'Value Alloc USD','LeadTime', 'Product Type', 'MPQ', 'Class','Usage Last Month', 'Usage 2 Mths ago', 'Usage 3 Mths ago', 'Total PBO Qty', 'Country Of Origin', 'Weight(grams)','Stock Asia', 'Stock Asia Available', 'Stock Canada', 'Stock Canada Available', 'Stock Europe', 'Stock Europe Available', 'Stock US', 'Stock US Available','Business Unit']]

In [16]:
bd2 = bd1.fillna(0)

In [17]:
bd2

,Ship To,Customer Name,Customer Part.,Mfr,Item No,Order Number,Date Ordered,Date Required,Qty Required,Qty Allocated,...,Weight(grams),Stock Asia,Stock Asia Available,Stock Canada,Stock Canada Available,Stock Europe,Stock Europe Available,Stock US,Stock US Available,Business Unit
0,JS005B00,JABIL VIETNAM CO. LTD.,189103664,DIO,7388556,BIM-JABIL VN-SMCI,01/15/2016,01/01/2030,6000,0,...,318.0,129000,42000,0,0,108000,105000,0,0,Small Signal Discretes
1,JS004000,JABIL VIETNAM CO. LTD,SND1DDE002302-NR,DIO,4456992,4508650451,12/14/2021,09/22/2023,117000,0,...,5152.0,825000,411000,0,0,231000,108000,558000,174000,Small Signal Discretes
2,JS004000,JABIL VIETNAM CO. LTD,CA763-00012-LC,DIO,7091728,4508909383,02/13/2022,09/09/2023,3000,0,...,340.0,30000,30000,0,0,3000,0,0,0,Discretes
3,JS004000,JABIL VIETNAM CO. LTD,SEECS-FT-20060-LF,DIO,7362841,4509263942,05/04/2022,09/09/2023,258000,0,...,6880.0,3648000,537000,0,0,582000,0,42000,30000,Small Signal Discretes
4,JS080200,JABIL VIETNAM CO. LTD.,SW5010155,DIO,2132320,1852055747,08/04/2022,09/12/2023,51000,0,...,6120.0,1776000,948000,0,0,0,0,0,0,Discretes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083,JS004000,JABIL VIETNAM CO. LTD,ZB-CR000457A01,SEM,8142023,4510992686,08/01/2023,01/27/2024,20000,0,...,550.0,20000,20000,0,0,0,0,0,0,Circuit Protection
1084,JS004000,JABIL VIETNAM CO. LTD,62711-45,DIO,1058804,4510994395,08/01/2023,12/06/2023,20000,0,...,7520.0,0,0,0,0,0,0,0,0,ANALOG
1085,JS004000,JABIL VIETNAM CO. LTD,62711-45,DIO,1058804,4510994396,08/01/2023,12/06/2023,5000,0,...,1880.0,0,0,0,0,0,0,0,0,ANALOG
1086,JS010600,JABIL VIETNAM CO. LTD.,192039313,NXP,6095769,1852141077,08/02/2023,06/10/2024,76000,0,...,2660.0,112000,0,0,0,0,0,0,0,ANALOG
1087,JS004000,JABIL VIETNAM CO. LTD,SNDHUA39594-NR,DIO,3067082,4510995656,08/02/2023,09/18/2023,30000,0,...,1080.0,170000,0,0,0,0,0,0,0,Small Signal Discretes

In [19]:
bd2.rename(columns={"Date Required":"date_req","Current Commit Date":"current_commit"})

,Ship To,Customer Name,Customer Part.,Mfr,Item No,Order Number,Date Ordered,date_req,Qty Required,Qty Allocated,...,Weight(grams),Stock Asia,Stock Asia Available,Stock Canada,Stock Canada Available,Stock Europe,Stock Europe Available,Stock US,Stock US Available,Business Unit
0,JS005B00,JABIL VIETNAM CO. LTD.,189103664,DIO,7388556,BIM-JABIL VN-SMCI,01/15/2016,01/01/2030,6000,0,...,318.0,129000,42000,0,0,108000,105000,0,0,Small Signal Discretes
1,JS004000,JABIL VIETNAM CO. LTD,SND1DDE002302-NR,DIO,4456992,4508650451,12/14/2021,09/22/2023,117000,0,...,5152.0,825000,411000,0,0,231000,108000,558000,174000,Small Signal Discretes
2,JS004000,JABIL VIETNAM CO. LTD,CA763-00012-LC,DIO,7091728,4508909383,02/13/2022,09/09/2023,3000,0,...,340.0,30000,30000,0,0,3000,0,0,0,Discretes
3,JS004000,JABIL VIETNAM CO. LTD,SEECS-FT-20060-LF,DIO,7362841,4509263942,05/04/2022,09/09/2023,258000,0,...,6880.0,3648000,537000,0,0,582000,0,42000,30000,Small Signal Discretes
4,JS080200,JABIL VIETNAM CO. LTD.,SW5010155,DIO,2132320,1852055747,08/04/2022,09/12/2023,51000,0,...,6120.0,1776000,948000,0,0,0,0,0,0,Discretes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083,JS004000,JABIL VIETNAM CO. LTD,ZB-CR000457A01,SEM,8142023,4510992686,08/01/2023,01/27/2024,20000,0,...,550.0,20000,20000,0,0,0,0,0,0,Circuit Protection
1084,JS004000,JABIL VIETNAM CO. LTD,62711-45,DIO,1058804,4510994395,08/01/2023,12/06/2023,20000,0,...,7520.0,0,0,0,0,0,0,0,0,ANALOG
1085,JS004000,JABIL VIETNAM CO. LTD,62711-45,DIO,1058804,4510994396,08/01/2023,12/06/2023,5000,0,...,1880.0,0,0,0,0,0,0,0,0,ANALOG
1086,JS010600,JABIL VIETNAM CO. LTD.,192039313,NXP,6095769,1852141077,08/02/2023,06/10/2024,76000,0,...,2660.0,112000,0,0,0,0,0,0,0,ANALOG
1087,JS004000,JABIL VIETNAM CO. LTD,SNDHUA39594-NR,DIO,3067082,4510995656,08/02/2023,09/18/2023,30000,0,...,1080.0,170000,0,0,0,0,0,0,0,Small Signal Discretes

In [18]:
#bd2.to_csv('C:\\Users\\DELL\\Documents\\Dissert Project\\Visualize\\cleaned_bd.csv', index = False)

In [20]:
from datetime import datetime